### ISSUE TITLE
请问，视频的转码参数在那个文件

### ISSUE THREAD

**Issue by rookie-z** [zhen-ke/ffmpegGUI#2]
请问，视频的转码参数在那个文件，我想根据需要来更改视频的质量的大小，让用户输入 ffmpeg 命令的形式执行转码操作的这个功能，我没有找到如何使用

**Comment by zhen-ke** [comment]
@rookie-z 

代码在`Main.vue` 第280行左右

```js
// 开始转码
startCommand() {
  // 基于fluentFFmpeg的转码
  if (this.activeTab === "video") {
    if (this.video === "") {
      this.msg("视频路径为空", "warning");
      return;
    }
    this.fluentFFmpeg(
      ffmpegBinary(this.video)
        .videoCodec(this.decoding)
        .videoBitrate(this.bit_rate) // 改变视频的比特率（提高或者减少就能改变视频质量和大小)
        .toFormat("mp4"),
      ".mp4"
    );
  }
```

默认我是通过调整视频的比特率改变视频质量和大小的（`videoBitrate`）, 我文档里有提到，先是读取默认的比特率然后提高1.5倍

**Comment by rookie-z** [comment]
其实使佣ffmpeg 的x264 可以使用 ffmpeg -i $di/$mz/$ss  -b:v 3000k -x264opts crf=20:keyint=25:ref=1:vbv-bufsize=20000:vbv-maxrate=4000 -ac 2 -ar 44100 -b:a 192k  /data/media-ok/$sj/$mz/$mz".mp4"
如果选择字幕： ffmpeg -i $di/$mz/$ss -vf subtitles=$di/$mz/$mz.ass -b:v 3000k -x264opts crf=20:keyint=25:ref=1:vbv-bufsize=20000:vbv-maxrate=4000 -ac 2 -ar 44100 -b:a 192k   /data/media-ok/$sj/$mz/$mz".mp4"
当然，参数大小可以按照需求来设置

**Comment by zhen-ke** [comment]
@rookie-z 谢谢，有空我试下

**Comment by rookie-z** [comment]
你是用的参数，利用Gpu来转码，我尝试过许多参数都不行，或者是还需要什么其他的东西，才能利用gpu转码

**Comment by zhen-ke** [comment]
@rookie-z 默认是我调用intel的内置GPU进行转码的，其它CPU由于没有相关硬件暂时无法测试，请问你是什么CPU？如果你想自定义硬件加速请参考我文档第一条，里面有讲是如何开启硬件加速的

**Comment by rookie-z** [comment]
英伟达，使用很多方法都不行，已经使用了你文档里面的，但是没有效果

**Comment by zhen-ke** [comment]
@rookie-z 我试过用自己的AMD显卡开启硬件加速，完全没问题，或者等等我进行更加测试，完善下代码，手上硬件有限暂时无法做更多测试

**Comment by rookie-z** [comment]
你已经实现了再windows下，ffmpeg 内嵌字幕的方法吗？

**Comment by zhen-ke** [comment]
@rookie-z 这个功能没实现，理论上是可以支持的，现在主要任务是把基础功能做好，然后在扩展新功能😏
