### ISSUE TITLE
希望能支持多线程的转码

### ISSUE THREAD

**Issue by im-dashan** [zhen-ke/ffmpegGUI#22]
希望能支持多线程的转码，还有文件夹和子文件夹的导入，

**Comment by zhen-ke** [comment]
@im-dashan 支持多线程转码，在命令行中，你可以使用 -threads 选项来指定使用的线程数。例如：
```bash
ffmpeg -i input.mp4 -c:v libx264 -threads 4 output.mp4
```
这里 `4` 是你希望使用的线程数。

文件夹和子文件夹的导入能详细描述下场景吗？

**Comment by im-dashan** [comment]
我的说法有误，不算是多线程，是可以在gui中导入文件夹和子文件夹，然后调用多个ffmpeg进程来同时处理多个任务，每个进程可以单独的多线程处理
![image](https://github.com/user-attachments/assets/1870f7cf-5621-4f89-88fc-0461a8f3884e)

**Comment by im-dashan** [comment]
有些可能需要批量转换视频或者音频，需要多个ffmpeg进程来同时处理多个内容，目前该项目的功能还很单一和基础，但是我看到了我需要命令控制，希望能添加更多的功能
