### ISSUE TITLE
预览版在合并视频的时候直接输出第一个视频

### ISSUE THREAD

**Issue by CronusLM** [zhen-ke/ffmpegGUI#8]
rt

**Comment by zhen-ke** [comment]
> rt

能提供复现过程么？

**Comment by CronusLM** [comment]
https://send.bgme.bid/download/fdfb9686e109d331/#SM3WeplOMljvrlorNDFq9Q
这是视频

**Comment by zhen-ke** [comment]
> https://send.bgme.bid/download/fdfb9686e109d331/#SM3WeplOMljvrlorNDFq9Q 这是视频

谢谢提醒，视频里的这个版本已经很久没维护了，目前已经采用 tauri 框架重写了整个逻辑， 但新版本还没有视频合并的功能，后续将会更新
